config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  Spree::Core::Engine.add_routes do
    get "/polityka-prywatnosci", to: "tos#index", as: :tos
    get "/zwroty", to: "returns#index", as: :returns
    get "home", to: "home#index"

    resources :payu
  end
end

app/views/spree/checkout/payment/_gateway.html.erb
<div class="payment-gateway">

  <% param_prefix = "payment_source[#{payment_method.id}]" %>

  <div class="payment-gateway-fields">
    <div class="mb-4 payment-gateway-field checkout-content-inner-field">
      <%= text_field_tag "#{param_prefix}[name]", "#{@order.bill_address_firstname} #{@order.bill_address_lastname}", { id: "name_on_card", class: 'spree-flat-input', placeholder: Spree.t(:name_on_card)} %>
    </div>

    <div class="mb-4 payment-gateway-field checkout-content-inner-field" data-hook="card_number">
      <% options_hash = Rails.env.production? ? {autocomplete: 'off'} : {} %>
      <%= text_field_tag "#{param_prefix}[number]", '', options_hash.merge(id: 'card_number', class: 'spree-flat-input cardNumber', size: 19, maxlength: 19, autocomplete: "off", placeholder: Spree.t(:card_number)) %>
      <span id="card_type" style="display:none;">
        ( <span id="looks_like" ><%= Spree.t(:card_type_is) %> <span id="type"></span></span>
          <span id="unrecognized"><%= Spree.t(:unrecognized_card_type) %></span>
        )
      </span>
    </div>
    <div class="payment-gateway-half-fields d-flex justify-content-between">
      <div class="payment-gateway-field checkout-content-inner-field" data-hook="card_expiration">
        <%= text_field_tag "#{param_prefix}[expiry]", '', id: 'card_expiry', class: 'spree-flat-input cardExpiry', placeholder: "MM / YY" %>
      </div>
      <div class="payment-gateway-field checkout-content-inner-field" data-hook="card_code">
        <%= text_field_tag "#{param_prefix}[verification_value]", '', options_hash.merge(id: 'card_code', class: 'spree-flat-input cardCode', size: 5, placeholder: Spree.t(:cvv)) %>
      </div>
    </div>

    <%= hidden_field_tag "#{param_prefix}[cc_type]", '', id: "cc_type", class: 'ccType' %>
  </div>
</div>

app/views/spree/checkout/payment/_payu.html.erb
<div class="text-center">
  <img width="150px" src="https://poland.payu.com/wp-content/uploads/sites/14/2020/05/PAYU_LOGO_LIME-990x640.png" />
  <%= link_to("Pay Now", payu_index_path(payment_method_id: payment_method.id), method: :post, id: "paypal_button") %>
  <br/>
</div>


<script type="text/javascript">
  
  SpreePaypalExpress = {
    updateSaveAndContinueVisibility: function() {
      if (this.isButtonHidden()) {
        $(this).trigger('hideSaveAndContinue')
      } else {
        $(this).trigger('showSaveAndContinue')
      }
    },
    isButtonHidden: function () {
      paymentMethod = this.checkedPaymentMethod();
      return (!$('#use_existing_card_yes:checked').length && SpreePaypalExpress.paymentMethodID && paymentMethod.val() == SpreePaypalExpress.paymentMethodID);
    },
    checkedPaymentMethod: function() {
      return $('div[data-hook="checkout_payment_step"] input[type="radio"][name="order[payments_attributes][][payment_method_id]"]:checked');
    },
    hideSaveAndContinue: function() {
      document.getElementsByClassName("checkout-content-save-continue-button")[0].hide();
    },
    showSaveAndContinue: function() {
      document.getElementsByClassName("checkout-content-save-continue-button")[0].show();
    }
  }

  document.ready(function() {
    button = document.getElementsByClassName("checkout-content-save-continue-button")[0];

    button.addEventListener("click", (e) => {
      e.preventDefault();
    });

    SpreePaypalExpress.updateSaveAndContinueVisibility();
    paymentMethods = $('div[data-hook="checkout_payment_step"] input[type="radio"]').click(function (e) {
      console.log("Clicked");
      SpreePaypalExpress.updateSaveAndContinueVisibility();
    });
    console.log(paymentMethods);
  })

</script>

app/views/spree/checkout/payment/_storecredit.html.erb
<% if @order.using_store_credit? %>
  <div class="d-flex flex-column mb-5" data-hook="checkout_payment_store_credit_success">
    <h3 class="store-credit-title"><%= Spree.t('store_credit.applicable_amount', amount: Spree::Money.new(@order.total_applicable_store_credit, { currency: @order.currency })).html_safe %></h3>
    <% if @order.covered_by_store_credit? %>
      <p><%= Spree.t('store_credit.remaining_amount', amount: @order.display_store_credit_remaining_after_capture).html_safe %></p>
    <% else %>
      <p><%= Spree.t('store_credit.additional_payment_needed', amount: @order.display_order_total_after_store_credit).html_safe %></p>
      <%= button_tag Spree.t('store_credit.remove'), name: 'remove_store_credit', class: 'store-credit-button continue btn btn-lg btn-primary font-weight-bold text-uppercase align-self-start' %>
    <% end %>
  </div>

<% elsif @order.could_use_store_credit? %>
  <div class="d-flex align-items-center justify-content-between mb-5" data-hook="checkout_payment_store_credit_available">
    <h2 class="store-credit-title"><%= Spree.t('store_credit.available_amount', amount: @order.display_total_available_store_credit).html_safe %></h2>
    <%= button_tag Spree.t('store_credit.apply'), name: 'apply_store_credit', class: 'store-credit-button continue btn btn-lg btn-primary font-weight-bold text-uppercase' %>
  </div>
<% end %>